version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 5
    groups:
      frontend-dev-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 5
    groups:
      backend-production-dependencies:
        dependency-type: production
      backend-development-dependencies:
        dependency-type: development
