-- Migration 0052: send activities to students and record their attempts
-- (docs/lesson-engine, stage G2). A dispatch is "this activity is open on the
-- class's devices now"; an attempt is one submission from one mapped device.
-- Attempts are append-only and idempotent per (device, client_attempt_id), so
-- a retried submit can never create a second result. Additive only (ADR-0008).

CREATE TABLE IF NOT EXISTS public.lesson_run_dispatches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lesson_run_id uuid NOT NULL REFERENCES public.lesson_runs(id) ON DELETE RESTRICT,
  block_id text NOT NULL,
  activity_instance_id text NOT NULL,
  opened_by uuid NOT NULL REFERENCES public.app_users(id) ON DELETE RESTRICT,
  opened_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz
);

-- At most one activity is open on the devices at a time.
CREATE UNIQUE INDEX IF NOT EXISTS lesson_run_dispatches_one_open_uq
  ON public.lesson_run_dispatches (lesson_run_id) WHERE closed_at IS NULL;
CREATE INDEX IF NOT EXISTS lesson_run_dispatches_run_idx
  ON public.lesson_run_dispatches (lesson_run_id, opened_at);

ALTER TABLE public.lesson_run_dispatches ENABLE ROW LEVEL SECURITY;

-- A dispatch may only be closed, once; nothing else about it changes.
CREATE OR REPLACE FUNCTION public.lesson_run_dispatches_guard()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'lesson run dispatches are never deleted';
  END IF;
  IF OLD.closed_at IS NOT NULL
     OR NEW.lesson_run_id IS DISTINCT FROM OLD.lesson_run_id
     OR NEW.block_id IS DISTINCT FROM OLD.block_id
     OR NEW.activity_instance_id IS DISTINCT FROM OLD.activity_instance_id
     OR NEW.opened_by IS DISTINCT FROM OLD.opened_by
     OR NEW.opened_at IS DISTINCT FROM OLD.opened_at THEN
    RAISE EXCEPTION 'dispatch % can only be closed, once', OLD.id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS lesson_run_dispatches_guard ON public.lesson_run_dispatches;
CREATE TRIGGER lesson_run_dispatches_guard
  BEFORE UPDATE OR DELETE ON public.lesson_run_dispatches
  FOR EACH ROW EXECUTE FUNCTION public.lesson_run_dispatches_guard();

CREATE TABLE IF NOT EXISTS public.activity_attempts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Generated by the device per submission; a retry reuses it.
  client_attempt_id uuid NOT NULL,
  lesson_run_id uuid NOT NULL REFERENCES public.lesson_runs(id) ON DELETE RESTRICT,
  dispatch_id uuid NOT NULL REFERENCES public.lesson_run_dispatches(id) ON DELETE RESTRICT,
  lesson_run_device_id uuid NOT NULL REFERENCES public.lesson_run_devices(id) ON DELETE RESTRICT,
  lesson_run_student_id uuid NOT NULL REFERENCES public.lesson_run_students(id) ON DELETE RESTRICT,
  block_id text NOT NULL,
  activity_instance_id text NOT NULL,
  mechanic text NOT NULL,
  telemetry text NOT NULL,
  attempt_no integer NOT NULL,
  answer_payload jsonb NOT NULL,
  correct integer NOT NULL,
  total integer NOT NULL,
  mistakes integer NOT NULL,
  normalized_score numeric(5, 4) NOT NULL,
  duration_sec integer,
  trust text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT activity_attempts_device_client_uq UNIQUE (lesson_run_device_id, client_attempt_id),
  CONSTRAINT activity_attempts_student_dispatch_no_uq UNIQUE (lesson_run_student_id, dispatch_id, attempt_no),
  CONSTRAINT activity_attempts_attempt_no_check CHECK (attempt_no >= 1),
  CONSTRAINT activity_attempts_counts_check
    CHECK (total >= 0 AND correct >= 0 AND correct <= total AND mistakes >= 0),
  CONSTRAINT activity_attempts_score_check CHECK (normalized_score >= 0 AND normalized_score <= 1),
  CONSTRAINT activity_attempts_telemetry_check CHECK (telemetry IN ('practice', 'checkpoint', 'evidence')),
  -- Games report their own result; only server-scored mechanics are verified.
  CONSTRAINT activity_attempts_trust_check CHECK (
    (mechanic = 'game' AND trust = 'client-unverified')
    OR (mechanic IN ('choice', 'truefalse', 'classify') AND trust = 'server-verified')
  )
);

CREATE INDEX IF NOT EXISTS activity_attempts_run_dispatch_idx
  ON public.activity_attempts (lesson_run_id, dispatch_id, lesson_run_student_id, attempt_no);

ALTER TABLE public.activity_attempts ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.activity_attempts_append_only()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  RAISE EXCEPTION 'activity_attempts is append-only';
END;
$$;

DROP TRIGGER IF EXISTS activity_attempts_append_only ON public.activity_attempts;
CREATE TRIGGER activity_attempts_append_only
  BEFORE UPDATE OR DELETE ON public.activity_attempts
  FOR EACH ROW EXECUTE FUNCTION public.activity_attempts_append_only();

ALTER TABLE public.lesson_run_events DROP CONSTRAINT IF EXISTS lesson_run_events_type_check;
ALTER TABLE public.lesson_run_events ADD CONSTRAINT lesson_run_events_type_check CHECK (type IN (
  'run_created', 'run_started', 'block_opened', 'activity_dispatched', 'activity_closed',
  'run_paused', 'run_resumed', 'run_finished', 'run_cancelled',
  'join_opened', 'join_closed', 'device_joined', 'device_mapped', 'device_unmapped', 'device_revoked'
));
