// ── Lesson Engine: evidence, outcome summaries and the lesson report (H) ─────
// Every summary is explainable: it is computed by a written rule from rows the
// teacher can open (evidence → attempt → activity → lesson version). There is
// no hidden mastery score, and nothing here is generated by AI.

import type { ActivitySpec, LearningOutcome, LessonDefinitionV1, LocalizedText } from './curriculum-lesson-schema.js'
import { choiceWrongPattern, type ChoicePattern } from './lesson-live.js'

export type EvidenceTrust = 'server-verified' | 'client-unverified' | 'teacher-observed'

export interface EvidenceRowInput {
  outcomeId: string
  evidenceRole: 'primary' | 'supporting'
  trust: EvidenceTrust
  score: number
}

/**
 * Evidence rows one attempt produces: only evidence activities, one row per
 * targeted outcome. A client-reported result is never recorded as primary.
 * A link that names `items` scores only those items; without per-item results
 * it records nothing rather than borrow the whole activity's score.
 */
export function evidenceRowsForAttempt(
  activity: ActivitySpec,
  attempt: { trust: EvidenceTrust; normalizedScore: number; itemResults?: { id: string; correct: boolean }[] | null },
): EvidenceRowInput[] {
  if (activity.telemetry !== 'evidence') return []
  const rows: EvidenceRowInput[] = []
  for (const link of activity.outcomes ?? []) {
    let score = attempt.normalizedScore
    if (link.items) {
      const wanted = new Set(link.items)
      const slice = (attempt.itemResults ?? []).filter(item => wanted.has(item.id))
      if (slice.length === 0) continue
      score = slice.filter(item => item.correct).length / slice.length
    }
    rows.push({
      outcomeId: link.outcomeId,
      evidenceRole: attempt.trust === 'client-unverified' ? 'supporting' : link.evidenceRole,
      trust: attempt.trust,
      score,
    })
  }
  return rows
}

export type OutcomeStatus = 'demonstrated' | 'progressing' | 'needs-support' | 'not-enough-evidence'

export const OUTCOME_STATUS_LABELS: Readonly<Record<OutcomeStatus, string>> = {
  'demonstrated': 'Продемонстровано',
  'progressing': 'Прогрес',
  'needs-support': 'Потрібна підтримка',
  'not-enough-evidence': 'Недостатньо даних',
}

/** Thresholds of the written rule (docs/lesson-engine/README.md, stage H). */
export const DEMONSTRATED_AT = 0.8
export const PROGRESSING_AT = 0.5

export interface SummaryEvidence {
  evidenceRole: 'primary' | 'supporting'
  trust: EvidenceTrust
  score: number
  observedAt: Date
}

/**
 * The rule: only the latest *primary, verified* evidence decides (server-scored
 * or teacher-observed). Supporting or client-reported evidence is shown to
 * the teacher but can never demonstrate an outcome on its own.
 */
export function summarizeOutcome(evidence: readonly SummaryEvidence[]): { status: OutcomeStatus; basis: string } {
  const decisive = evidence
    .filter(e => e.evidenceRole === 'primary' && e.trust !== 'client-unverified')
    .sort((a, b) => a.observedAt.getTime() - b.observedAt.getTime())
  const latest = decisive[decisive.length - 1]
  if (!latest) {
    return {
      status: 'not-enough-evidence',
      basis: evidence.length > 0 ? 'Є лише допоміжні дані — основного доказу немає.' : 'Доказів немає.',
    }
  }
  const percent = Math.round(latest.score * 100)
  if (latest.score >= DEMONSTRATED_AT) return { status: 'demonstrated', basis: `Останній основний доказ: ${percent}% (поріг ${DEMONSTRATED_AT * 100}%).` }
  if (latest.score >= PROGRESSING_AT) return { status: 'progressing', basis: `Останній основний доказ: ${percent}% (між ${PROGRESSING_AT * 100}% і ${DEMONSTRATED_AT * 100}%).` }
  return { status: 'needs-support', basis: `Останній основний доказ: ${percent}% (нижче ${PROGRESSING_AT * 100}%).` }
}

export interface LessonReportInput {
  run: { status: string; className: string; lessonPublishedVersion: number; startedAt: Date | null; finishedAt: Date | null }
  lesson: LessonDefinitionV1
  outcomes: Record<string, LearningOutcome>
  students: { id: string; label: string | null }[]
  mappedStudentIds: ReadonlySet<string>
  dispatches: { id: string; blockId: string; activityInstanceId: string }[]
  attempts: {
    id: string
    dispatchId: string
    lessonRunStudentId: string
    activityInstanceId: string
    attemptNo: number
    correct: number
    total: number
    normalizedScore: number
    trust: EvidenceTrust
    answerPayload: Record<string, unknown>
    createdAt: Date
  }[]
  evidence: {
    lessonRunStudentId: string
    activityAttemptId: string
    outcomeId: string
    evidenceRole: 'primary' | 'supporting'
    trust: EvidenceTrust
    score: number
    observedAt: Date
  }[]
}

function blockTitle(lesson: LessonDefinitionV1, blockId: string, fallback: string): string {
  const block = lesson.blocks.find(b => b.id === blockId)
  const headline = block?.presentation?.headline?.uk
  const heading = (block?.content as { heading?: LocalizedText } | undefined)?.heading?.uk
  return headline ?? heading ?? fallback
}

/** Deterministic, factual comment the teacher can edit — no invented facts. */
export function teacherCommentDraft(label: string, outcomes: { title: string; status: OutcomeStatus }[], answered: number): string {
  if (answered === 0 && outcomes.every(o => o.status === 'not-enough-evidence')) {
    return `${label}: у цьому уроці результатів немає.`
  }
  const by = (status: OutcomeStatus) => outcomes.filter(o => o.status === status).map(o => `«${o.title}»`)
  const parts: string[] = []
  const shown = by('demonstrated')
  const growing = by('progressing')
  const support = by('needs-support')
  const missing = by('not-enough-evidence')
  if (shown.length) parts.push(`продемонстрував(ла) ${shown.join(', ')}`)
  if (growing.length) parts.push(`є прогрес: ${growing.join(', ')}`)
  if (support.length) parts.push(`потрібна підтримка: ${support.join(', ')}`)
  if (missing.length) parts.push(`бракує даних: ${missing.join(', ')}`)
  parts.push(`виконано завдань: ${answered}`)
  return `${label}: ${parts.join('; ')}.`
}

export function lessonReport(input: LessonReportInput) {
  const { lesson } = input
  const activities = new Map<string, ActivitySpec>()
  for (const block of lesson.blocks) if (block.type === 'activity') activities.set(block.activity.instanceId, block.activity)
  const titleOfDispatch = new Map(input.dispatches.map(d => [d.id, blockTitle(lesson, d.blockId, d.activityInstanceId)]))
  const attemptsById = new Map(input.attempts.map(a => [a.id, a]))

  const outcomes = lesson.learningOutcomes.map(link => {
    const outcome = input.outcomes[link.outcomeId]
    return { id: link.outcomeId, role: link.role, code: outcome?.code ?? link.outcomeId, title: outcome?.title.uk ?? link.outcomeId }
  })

  const roster = input.students.filter(s => s.label !== null)
  const latestPerStudent = (dispatchId: string) => roster
    .map(s => input.attempts.filter(a => a.dispatchId === dispatchId && a.lessonRunStudentId === s.id).sort((a, b) => a.attemptNo - b.attemptNo).pop())
    .filter((a): a is LessonReportInput['attempts'][number] => Boolean(a))

  const activityStats = input.dispatches.map(dispatch => {
    const activity = activities.get(dispatch.activityInstanceId)
    const latest = latestPerStudent(dispatch.id)
    const average = latest.length ? latest.reduce((sum, a) => sum + a.normalizedScore, 0) / latest.length : null
    const pattern: ChoicePattern | null = activity ? choiceWrongPattern(activity, latest) : null
    return {
      dispatchId: dispatch.id,
      blockId: dispatch.blockId,
      activityInstanceId: dispatch.activityInstanceId,
      title: titleOfDispatch.get(dispatch.id)!,
      telemetry: activity?.telemetry ?? null,
      mechanic: activity?.mechanic ?? null,
      answered: latest.length,
      of: roster.length,
      averageScore: average,
      pattern,
    }
  })

  const students = roster.map(student => {
    const mine = input.attempts.filter(a => a.lessonRunStudentId === student.id)
    const perActivity = input.dispatches.map(dispatch => {
      const tries = mine.filter(a => a.dispatchId === dispatch.id).sort((a, b) => a.attemptNo - b.attemptNo)
      const last = tries[tries.length - 1]
      return {
        dispatchId: dispatch.id,
        title: titleOfDispatch.get(dispatch.id)!,
        attempts: tries.length,
        correct: last?.correct ?? null,
        total: last?.total ?? null,
        trust: last?.trust ?? null,
      }
    })
    const outcomeRows = outcomes.map(outcome => {
      const evidence = input.evidence
        .filter(e => e.lessonRunStudentId === student.id && e.outcomeId === outcome.id)
        .sort((a, b) => a.observedAt.getTime() - b.observedAt.getTime())
      const summary = summarizeOutcome(evidence)
      return {
        outcomeId: outcome.id,
        status: summary.status,
        label: OUTCOME_STATUS_LABELS[summary.status],
        basis: summary.basis,
        // The trace: each row opens to the attempt, its activity and the lesson version.
        evidence: evidence.map(e => {
          const attempt = attemptsById.get(e.activityAttemptId)
          return {
            attemptId: e.activityAttemptId,
            activityInstanceId: attempt?.activityInstanceId ?? null,
            activityTitle: attempt ? titleOfDispatch.get(attempt.dispatchId) ?? attempt.activityInstanceId : null,
            attemptNo: attempt?.attemptNo ?? null,
            correct: attempt?.correct ?? null,
            total: attempt?.total ?? null,
            score: e.score,
            trust: e.trust,
            evidenceRole: e.evidenceRole,
            observedAt: e.observedAt,
          }
        }),
      }
    })
    const answered = perActivity.filter(a => a.attempts > 0).length
    return {
      lessonRunStudentId: student.id,
      label: student.label!,
      participated: input.mappedStudentIds.has(student.id) || mine.length > 0,
      activities: perActivity,
      missing: perActivity.filter(a => a.attempts === 0).map(a => a.title),
      outcomes: outcomeRows,
      comment: teacherCommentDraft(
        student.label!,
        outcomeRows.map(o => ({ title: outcomes.find(x => x.id === o.outcomeId)!.title, status: o.status })),
        answered,
      ),
    }
  })

  return {
    run: {
      status: input.run.status,
      className: input.run.className,
      lessonTitle: lesson.title,
      lessonId: lesson.id,
      lessonPublishedVersion: input.run.lessonPublishedVersion,
      startedAt: input.run.startedAt,
      finishedAt: input.run.finishedAt,
    },
    rule: { demonstratedAt: DEMONSTRATED_AT, progressingAt: PROGRESSING_AT },
    outcomes,
    activities: activityStats,
    students,
  }
}
