import type { FoStatement } from './fact-opinion-game.js'

// Контент гри «Факт чи думка?» — перенесено з temp/new/fact-or-opinion
// (редакторські правки: дитяча лексика, категорія «міф» для забобонів L2,
// точні URL джерел зі старої версії). Згенеровано скриптом, далі — правити тут.
//
// Рівень 1 (1–2 клас): факт / думка. Рівень 2 (2–4 клас): факт / думка / міф.
// Джерела: для частини тверджень L1 URL ще немає (лише назва довідника) —
// контентний борг, ігровий UI показує посилання тільки коли воно є.

export const FO_LEVEL1_STATEMENTS: FoStatement[] = [
  {"id":"fact-l1-sun","category":"fact","text":"Сонце — це зірка.","explanation":"Це можна перевірити. Вчені довели, що Сонце — найближча до нас зірка.","sourceTitle":"Енциклопедія Сучасної України — Зорі","sourceUrl":"https://esu.com.ua/article-17092","sourceLanguage":"uk"},
  {"id":"fact-l1-ice","category":"fact","text":"Лід — це замерзла вода.","explanation":"Це факт. Якщо покласти воду в холодильник, вона стане льодом.","sourceTitle":"Велика українська енциклопедія — Вода","sourceUrl":"https://vue.gov.ua/Вода","sourceLanguage":"uk"},
  {"id":"fact-l1-insects","category":"fact","text":"Комахи мають шість ніжок.","explanation":"Це можна порахувати. Усі комахи мають рівно шість ніг.","sourceTitle":"Britannica — Insect","sourceUrl":"https://www.britannica.com/animal/insect","sourceLanguage":"en"},
  {"id":"fact-l1-kyiv","category":"fact","text":"Столиця України — місто Київ.","explanation":"Це факт, який записаний у законах нашої держави.","sourceTitle":"Конституція України, стаття 20","sourceUrl":"https://zakon.rada.gov.ua/laws/show/254%D0%BA/96-%D0%B2%D1%80#Text","sourceLanguage":"uk"},
  {"id":"fact-l1-cow","category":"fact","text":"Корова дає молоко.","explanation":"Це біологічний факт. З коров'ячого молока роблять сир і масло.","sourceTitle":"Енциклопедія тварин","sourceLanguage":"uk"},
  {"id":"fact-l1-apple","category":"fact","text":"Яблука ростуть на деревах.","explanation":"Це можна побачити в саду. Яблуня — це фруктове дерево.","sourceTitle":"Ботанічний довідник","sourceLanguage":"uk"},
  {"id":"fact-l1-fish","category":"fact","text":"Риби живуть у воді.","explanation":"Це факт. Риби дихають під водою за допомогою зябер.","sourceTitle":"Енциклопедія природи","sourceLanguage":"uk"},
  {"id":"fact-l1-birds","category":"fact","text":"Птахи мають крила.","explanation":"Це анатомічний факт. Крила є навіть у птахів, які не літають, — як пінгвін чи страус.","sourceTitle":"Орнітологія для дітей","sourceLanguage":"uk"},
  {"id":"fact-l1-snow","category":"fact","text":"Сніг білого кольору.","explanation":"Це можна перевірити очима. Сніжинки відбивають світло, тому здаються білими.","sourceTitle":"Фізика для малюків","sourceLanguage":"uk"},
  {"id":"fact-l1-week","category":"fact","text":"У тижні сім днів.","explanation":"Це календарний факт. Після неділі завжди настає понеділок.","sourceTitle":"Календар","sourceLanguage":"uk"},
  {"id":"fact-l1-carrot","category":"fact","text":"Морква — це овоч.","explanation":"Це ботанічний факт. Вона росте в землі на городі.","sourceTitle":"Словник української мови","sourceLanguage":"uk"},
  {"id":"fact-l1-dog","category":"fact","text":"Собаки мають чотири лапи.","explanation":"Це можна порахувати. Собаки належать до чотирилапих тварин.","sourceTitle":"Біологія тварин","sourceLanguage":"uk"},
  {"id":"fact-l1-frog","category":"fact","text":"Жаби вміють стрибати.","explanation":"Це факт. Їхні задні лапки дуже сильні.","sourceTitle":"Зоологія","sourceLanguage":"uk"},
  {"id":"fact-l1-night","category":"fact","text":"Вночі темніше, ніж вдень.","explanation":"Це можна побачити. Вночі на небі немає Сонця.","sourceTitle":"Астрономія для дітей","sourceLanguage":"uk"},
  {"id":"fact-l1-sugar","category":"fact","text":"Цукор солодкий на смак.","explanation":"Це кулінарний факт. Його додають у чай, щоб він став солодким.","sourceTitle":"Хімія продуктів","sourceLanguage":"uk"},
  {"id":"fact-l1-rain","category":"fact","text":"Дощ падає з хмар.","explanation":"Це природне явище. Вода збирається в хмарах і падає краплями.","sourceTitle":"Метеорологія","sourceLanguage":"uk"},
  {"id":"fact-l1-cat-sound","category":"fact","text":"Коти вміють нявкати.","explanation":"Це факт. Так вони спілкуються з людьми.","sourceTitle":"Етологія тварин","sourceLanguage":"uk"},
  {"id":"fact-l1-triangle","category":"fact","text":"Трикутник має три кути.","explanation":"Це математичний факт. Якщо кутів чотири, це вже інша фігура.","sourceTitle":"Геометрія","sourceLanguage":"uk"},
  {"id":"fact-l1-lemon","category":"fact","text":"Стиглі лимони жовтого кольору.","explanation":"Це можна побачити в магазині або на дереві. Недостиглі лимони бувають зеленими.","sourceTitle":"Ботаніка","sourceLanguage":"uk"},
  {"id":"fact-l1-winter","category":"fact","text":"Зима настає після осені.","explanation":"Це календарний факт. Пори року йдуть одна за одною.","sourceTitle":"Природознавство","sourceLanguage":"uk"},
  {"id":"opinion-l1-icecream","category":"opinion","text":"Морозиво — найсмачніша їжа.","explanation":"Це смак. Комусь більше подобаються яблука або піца."},
  {"id":"opinion-l1-cats","category":"opinion","text":"Усі котики дуже милі.","explanation":"Це думка. Деякі люди бояться котів."},
  {"id":"opinion-l1-winter","category":"opinion","text":"Зима набагато краща за літо.","explanation":"Це особистий вибір. Хтось любить грати в сніжки, а хтось — плавати."},
  {"id":"opinion-l1-spiders","category":"opinion","text":"Павуки дуже страшні.","explanation":"Це емоція. Для вчених павуки не страшні, а цікаві."},
  {"id":"opinion-l1-blue","category":"opinion","text":"Синій колір найкрасивіший.","explanation":"Це оцінка. Іншим людям подобається червоний або зелений."},
  {"id":"opinion-l1-cartoons","category":"opinion","text":"Усі мультики смішні.","explanation":"Це узагальнення. Бувають сумні або нудні мультики."},
  {"id":"opinion-l1-pizza","category":"opinion","text":"Піца краща за суп.","explanation":"Це смак. Деякі діти більше люблять гарячий суп."},
  {"id":"opinion-l1-dogs","category":"opinion","text":"Собаки — найкращі друзі.","explanation":"Це думка. Для когось найкращий друг — це папуга."},
  {"id":"opinion-l1-monday","category":"opinion","text":"Понеділок — поганий день.","explanation":"Це емоція. Дні тижня не бувають поганими чи хорошими."},
  {"id":"opinion-l1-drawing","category":"opinion","text":"Малювання — найкращий урок.","explanation":"Це особистий вибір. Хтось більше любить співати чи бігати."},
  {"id":"opinion-l1-chocolate","category":"opinion","text":"Усі діти люблять шоколад.","explanation":"Це помилка. Є діти, яким шоколад не подобається."},
  {"id":"opinion-l1-rain-sad","category":"opinion","text":"Дощ робить людей сумними.","explanation":"Це думка. Багато людей люблять гуляти під дощем."},
  {"id":"opinion-l1-singing","category":"opinion","text":"Співати дуже легко.","explanation":"Це оцінка. Для когось співати складно."},
  {"id":"opinion-l1-toys","category":"opinion","text":"Іграшки — найкращий подарунок.","explanation":"Це думка. Хтось хоче отримати цікаву книжку."},
  {"id":"opinion-l1-bears","category":"opinion","text":"Усі ведмеді злі.","explanation":"Це узагальнення. Тварини просто захищають свою територію."},
  {"id":"opinion-l1-milk","category":"opinion","text":"Молоко зовсім несмачне.","explanation":"Це смак. Багато дітей п'ють молоко із задоволенням."},
  {"id":"opinion-l1-autumn","category":"opinion","text":"Осінь — нудна пора.","explanation":"Це емоція. Восени можна збирати красиве листя."},
  {"id":"opinion-l1-sleep","category":"opinion","text":"Спати вдень погано.","explanation":"Це оцінка. Маленьким дітям денний сон дає сили."},
  {"id":"opinion-l1-dresses","category":"opinion","text":"Сукні гарніші за штани.","explanation":"Це смак. Одяг обирають за зручністю та вподобаннями."},
  {"id":"opinion-l1-apples","category":"opinion","text":"Яблука смачніші за банани.","explanation":"Це особистий смак. Фрукти подобаються по-різному."},
]

export const FO_LEVEL2_STATEMENTS: FoStatement[] = [
  {"id":"fact-l2-earth","category":"fact","text":"Земля — третя планета від Сонця.","explanation":"Це факт астрономії. Меркурій і Венера знаходяться ближче до Сонця.","sourceTitle":"Велика українська енциклопедія — Земля","sourceUrl":"https://vue.gov.ua/Земля","sourceLanguage":"uk"},
  {"id":"fact-l2-ocean","category":"fact","text":"Океан покриває понад 70% поверхні Землі.","explanation":"Це вимірюваний факт. Вода займає більшу частину нашої планети.","sourceTitle":"Основи океанології — навчальний посібник","sourceUrl":"https://ev.vue.gov.ua/wp-content/uploads/2023/11/Osnovy-okeanolohii-2008.pdf","sourceLanguage":"uk"},
  {"id":"fact-l2-photosynthesis","category":"fact","text":"Під час фотосинтезу рослини виділяють кисень.","explanation":"Це біологічний процес. Рослини поглинають вуглекислий газ, а виділяють кисень.","sourceTitle":"Енциклопедія Сучасної України — Міксотрофи","sourceUrl":"https://esu.com.ua/article-69330","sourceLanguage":"uk"},
  {"id":"fact-l2-water-boil","category":"fact","text":"Вода кипить приблизно за температури 100 °C.","explanation":"Це фізичний факт для нормального атмосферного тиску.","sourceTitle":"Велика українська енциклопедія — Вода","sourceUrl":"https://vue.gov.ua/Вода","sourceLanguage":"uk"},
  {"id":"fact-l2-everest","category":"fact","text":"Еверест — найвища гора світу за висотою над рівнем моря.","explanation":"Це географічний факт. Її висота становить 8848 метрів.","sourceTitle":"Вікіпедія — Еверест","sourceUrl":"https://uk.wikipedia.org/wiki/Еверест","sourceLanguage":"uk"},
  {"id":"fact-l2-cheetah","category":"fact","text":"Гепард — найшвидша наземна тварина.","explanation":"Це підтверджено спостереженнями. Гепард пристосований до швидкого бігу на короткі дистанції.","sourceTitle":"National Geographic Kids — Cheetah","sourceUrl":"https://kids.nationalgeographic.com/animals/mammals/facts/cheetah","sourceLanguage":"en"},
  {"id":"fact-l2-octopus","category":"fact","text":"У восьминога три серця.","explanation":"Це анатомічний факт. Два серця рухають кров через зябра, а третє — по тілу.","sourceTitle":"Smithsonian Magazine — Octopuses","sourceUrl":"https://www.smithsonianmag.com/science-nature/ten-wild-facts-about-octopuses-they-have-three-hearts-big-brains-and-blue-blood-7625828/","sourceLanguage":"en"},
  {"id":"fact-l2-human-water","category":"fact","text":"Тіло дорослої людини приблизно на 60% складається з води.","explanation":"Це медичний факт. Відсоток може незначно коливатися залежно від віку.","sourceTitle":"USGS — Water and the Human Body","sourceUrl":"https://www.usgs.gov/water-science-school/science/water-you-water-and-human-body","sourceLanguage":"en"},
  {"id":"fact-l2-lungs","category":"fact","text":"Людина дихає за допомогою легень.","explanation":"Це біологічний факт. Легені допомагають отримувати кисень із повітря.","sourceTitle":"MedlinePlus — Lungs and Breathing","sourceUrl":"https://medlineplus.gov/lungsandbreathing.html","sourceLanguage":"en"},
  {"id":"fact-l2-alphabet","category":"fact","text":"В українській абетці 33 літери.","explanation":"Це факт із мовознавства, який легко перевірити за словником.","sourceTitle":"Енциклопедія Сучасної України — Абетка","sourceUrl":"https://esu.com.ua/article-42173","sourceLanguage":"uk"},
  {"id":"fact-l2-magnet","category":"fact","text":"Магніт притягує залізо.","explanation":"Це фізичний факт. Залізо має властивість взаємодіяти з магнітним полем.","sourceTitle":"Britannica — Magnetism","sourceUrl":"https://www.britannica.com/science/magnetism","sourceLanguage":"en"},
  {"id":"fact-l2-bats","category":"fact","text":"Кажани — єдині ссавці, які вміють літати.","explanation":"Це науковий факт. Вони вигодовують дитинчат молоком і мають активний політ.","sourceTitle":"Bat Conservation International — Bats 101","sourceUrl":"https://www.batcon.org/about-bats/bats-101/","sourceLanguage":"en"},
  {"id":"fact-l2-penguins","category":"fact","text":"Пінгвіни живуть переважно в Південній півкулі.","explanation":"Це географічний факт. Більшість видів мешкає на південь від екватора.","sourceTitle":"WWF — Penguin","sourceUrl":"https://www.worldwildlife.org/species/penguin","sourceLanguage":"en"},
  {"id":"fact-l2-leap-year","category":"fact","text":"У високосному році 366 днів.","explanation":"Це факт календаря. Додатковий день з'являється у лютому раз на чотири роки.","sourceTitle":"Britannica — Leap year","sourceUrl":"https://www.britannica.com/science/leap-year-calendar","sourceLanguage":"en"},
  {"id":"fact-l2-sahara","category":"fact","text":"Сахара — найбільша спекотна пустеля у світі.","explanation":"Це географічний факт. Антарктида більша, але вона є холодною пустелею.","sourceTitle":"Britannica — Sahara","sourceUrl":"https://www.britannica.com/place/Sahara-desert-Africa","sourceLanguage":"en"},
  {"id":"fact-l2-mars","category":"fact","text":"Марс часто називають Червоною планетою.","explanation":"Це астрономічний факт. Червоний колір виникає через велику кількість оксиду заліза (іржі) в ґрунті.","sourceTitle":"NASA — Mars Facts","sourceUrl":"https://science.nasa.gov/mars/facts/","sourceLanguage":"en"},
  {"id":"fact-l2-camel","category":"fact","text":"Верблюди зберігають у горбах жир, а не воду.","explanation":"Це біологічний факт. Запаси жиру допомагають їм виживати без їжі у пустелі.","sourceTitle":"National Geographic Kids — Bactrian Camel","sourceUrl":"https://kids.nationalgeographic.com/animals/mammals/facts/bactrian-camel","sourceLanguage":"en"},
  {"id":"fact-l2-ostrich","category":"fact","text":"Страус не літає, але дуже швидко бігає.","explanation":"Це факт. Їхня анатомія пристосована до бігу, а не до польоту.","sourceTitle":"San Diego Zoo — Ostrich","sourceUrl":"https://animals.sandiegozoo.org/animals/ostrich","sourceLanguage":"en"},
  {"id":"fact-l2-paper","category":"fact","text":"Папір часто виготовляють із деревини.","explanation":"Це технологічний факт. Деревинна целюлоза є основним матеріалом для паперу.","sourceTitle":"Britannica — Paper","sourceUrl":"https://www.britannica.com/technology/paper","sourceLanguage":"en"},
  {"id":"fact-l2-blood","category":"fact","text":"Кров людини має червоний колір.","explanation":"Це медичний факт. Колір зумовлений наявністю гемоглобіну.","sourceTitle":"MedlinePlus — Blood","sourceUrl":"https://medlineplus.gov/blood.html","sourceLanguage":"en"},
  {"id":"opinion-l2-math","category":"opinion","text":"Математика — найважчий шкільний предмет.","explanation":"Це особиста оцінка. Для одних учнів математика легка, а мови — складні."},
  {"id":"opinion-l2-blackcat","category":"myth","text":"Чорна кішка, яка перейшла дорогу, приносить нещастя.","explanation":"Це забобон. Колір шерсті котика ніяк не впливає на події в житті людини."},
  {"id":"opinion-l2-books","category":"opinion","text":"Читати книгу завжди цікавіше, ніж дивитися фільм.","explanation":"Це особистий вибір. Комусь більше подобається дивитися фільм, і це теж добре."},
  {"id":"opinion-l2-games","category":"opinion","text":"Ігри на телефоні — це марна трата часу.","explanation":"Це узагальнення. Деякі ігри розвивають логіку, пам'ять або реакцію."},
  {"id":"opinion-l2-mirror","category":"myth","text":"Розбите дзеркало означає сім років невдач.","explanation":"Це народний забобон. Розбите дзеркало — просто розбите скло, воно не змінює майбутнє."},
  {"id":"opinion-l2-music","category":"opinion","text":"Класична музика краща за сучасну.","explanation":"Це естетична оцінка. Різні стилі музики подобаються різним людям."},
  {"id":"opinion-l2-horseshoe","category":"myth","text":"Знайти підкову — до щастя.","explanation":"Це міф. Металевий виріб для коней не може впливати на успіх людини."},
  {"id":"opinion-l2-salt","category":"myth","text":"Якщо розсипати сіль, обов'язково буде сварка.","explanation":"Це забобон. Розсипана сіль створює лише безлад на столі."},
  {"id":"opinion-l2-spring","category":"opinion","text":"Весна — найкрасивіша пора року.","explanation":"Це особисте враження. Комусь найкрасивішою здається зима або осінь."},
  {"id":"opinion-l2-language","category":"opinion","text":"Вивчати іноземну мову дуже легко.","explanation":"Це оцінка. Комусь мови даються легко, а комусь потрібно більше часу — і це нормально."},
  {"id":"opinion-l2-sweep","category":"myth","text":"Вимітати сміття ввечері — це до втрати грошей.","explanation":"Це забобон. Прибирання ввечері ніяк не повʼязане з грошима."},
  {"id":"opinion-l2-football","category":"opinion","text":"Футбол — найцікавіший вид спорту у світі.","explanation":"Це думка. Для багатьох людей теніс або шахи набагато цікавіші."},
  {"id":"opinion-l2-oatmeal","category":"opinion","text":"На сніданок завжди потрібно їсти вівсянку.","explanation":"Це особиста порада. Раціон харчування має бути різноманітним і залежати від потреб організму."},
  {"id":"opinion-l2-mouse","category":"opinion","text":"Комп'ютерна миша завжди зручніша за тачпад.","explanation":"Це питання звички. Багато спеціалістів працюють виключно на тачпаді."},
  {"id":"opinion-l2-star","category":"myth","text":"Зірка, що падає, виконує бажання.","explanation":"Це красивий міф. «Падаюча зірка» — це метеор, який згорає в атмосфері."},
  {"id":"opinion-l2-roses","category":"opinion","text":"Троянди — найкрасивіші квіти.","explanation":"Це смакова перевага. Немає об'єктивного вимірювача краси для рослин."},
  {"id":"opinion-l2-pe","category":"opinion","text":"Уроки фізкультури — найвеселіші в школі.","explanation":"Це оцінка. Для учнів, які люблять конструювання, найвеселішою може бути інформатика."},
  {"id":"opinion-l2-crow","category":"myth","text":"Вороняче каркання віщує біду.","explanation":"Це забобон. Каркання — просто спосіб спілкування птахів, воно нічого не віщує."},
  {"id":"opinion-l2-clover","category":"myth","text":"Чотирилиста конюшина приносить удачу.","explanation":"Це прикмета. Рідкісний листочок цікаво знайти, але він не змінює події в житті."},
  {"id":"opinion-l2-vacation","category":"opinion","text":"Канікули завжди проходять занадто швидко.","explanation":"Це відчуття. Годинник на канікулах іде так само — просто веселий час пролітає непомітно."},
]
